### PR TITLE
Group2 cache utilization

### PR DESCRIPTION
**Pull request by Murmeldyret**
The cache has been fully implemented and will be used if the client sends an empty vector in the components field together with a hash.

Tests has been made to ensure that no two users can interfere with each other.

**Upon merge**, these two PR's should be merged as well:
- https://github.com/ECDAR-AAU-SW-P5/Ecdar-ProtoBuf/pull/1
- https://github.com/ECDAR-AAU-SW-P5/Ecdar-Test/pull/1

@ECDAR-AAU-SW-P5/group2

### CODE REVIEW

**Comment by frederikja163** [comment]
Is this pull request ready for review?

**Comment by Murmeldyret** [comment]
> Is this pull request ready for review?

Yes.

**Review by Aavild — CHANGES_REQUESTED** [review]
Since these are modifications to the protobufer you need to run the Ecdar-Test framework and see that this doesn't introduce new issues

**Review by Aavild — APPROVED** [review]
with [Protobuf submodule pointer update](https://github.com/ECDAR-AAU-SW-P5/Ecdar-Test) it looks good

**Review by williamwoldum — APPROVED** [review]

**Review by sabotack — APPROVED** [review]

**Review by rasmusq — APPROVED** [review]

**Pull request merged**
